#ENG: Plugin and Config made by MatzeLP
#DEU: Plugin und Config von MatzeLP


#ENG: Allow Random Nick
#DEU: Erlaube einen Zufälligen Nick zu benutzen

random-nick: true

#ENG: List here all your random Nicks
#DEU: Liste hier alle Zufälligen Nicks auf

random-nicks:
  - MinhBiGay
  - MrQuangTeo
  - RBplugin
  - Yametee

#ENG: Allow Custom Nick
#DEU: Erlaube einen Eigenen Nick zu benutzen

custom-nick: true
not-allow-custom-nicks:
  - ServerTeam
  - HateYou
  - Hacker
  - Sex
  - sex
  - Jav
  - jav
  - Kimochi
  - kimochi
  - Hentai
  - hentai
  - TranMinh12032k5
  - tranminh12032k5

#######################################################
########################- UI -#########################
#######################################################

#ENG: Here you can configure the UI. Use \n for a new Line
#DEU: Hier kannst du die UI Einstellen. Benutze \n für eine neue Zeile

Main-Title: "§l【 MENU ĐỔI TÊN §6Ｖip §r§l】"
Main-Button-CustomNick: "§l§cĐặt tên tự chọn"
Main-Button-RandomNick: "§l§cĐặt tên ngẫu nhiên"
Main-Button-Close: "§l【 §cTHOÁT §r§l】"

CustomNick-Title: "§l【 ĐẶT TÊN TỰ CHỌN §r§l】"

#######################################################
#####################- Messages -######################
#######################################################

#ENG: Here you can configure all the Messages
#DEU: Hier kannst du alle Narichten bearbeiten

nick-set: "§7➢ §aTên của bạn đã được đặt là §e【{nick}】"
not-allowed-nick: "§7➢ §cTên này bị cấm, hãy chọn tên khác"


