---
plugin-name: essentalsTp+
sqlite-dbname: essentials_tp
tpa-here-cooldown: "30"
tp-home-cooldown: "5"
tp-warp-cooldown: "5"
tp-spawn-cooldown: "5"
MOTD: trời đất dung hoa vạn vật sinh sôi
wild-MaxX: "3000"
wild-MaxY: "3000"
bed-sets-home: "true"
Lang_invalid_usage: 'INVALID USAGE:'
Lang_command_only_use_ingame: This command can only be used in the game.
Lang_no_permissions: '[EssentialsTP] No permission.'
Lang_teleport_home: §e【EssentialsTP】 §fĐã dịch chuyển về nhà §fcủa bạn.
Lang_teleport_spawn: §e【EssentialsTP】 §fĐã dịch chuyển tới spawn.
Lang_teleport_wild: §e【EssentialsTP】 §fĐang dịch chuyển tới 1 nơi ngẫu nhiên.
Lang_teleport_death: §e【EssentialsTP】 §fĐã dịch chuyển tới nơi bạn vừa chết.
Lang_no_spawn_set: §e【EssentialsTP】 §fKhông có nơi hồi sinh §fcho thế giới này. Sử
  dụng nơi hồi §fsinh chính.
Lang_teleport_spawn_original: §e【EssentialsTP】 §fĐang dịch chuyển tới nơi hồi sinh§f
  chính.
Lang_spawn_set: §e【EssentialsTP】 §fĐã chỉnh khu spawn.
Lang_your_homes: §e【EssentialsTP】 §fNhà của bạn:§f
Lang_no_home_set: §e【EssentialsTP】 §fBạn chưa chỉnh khu nhà nào.
Lang_no_home_name: §e【EssentialsTP】 §cBạn không có khu nhà nào trùng tên này.
Lang_home_set: §e【EssentialsTP】 §fNhà được đặt là§6
Lang_home_delete_1: §fTên nhà:§6
Lang_home_delete_2: §fđã bị xoá.
Lang_no_teleport_self: §e【EssentialsTP】 §fBạn không thể dịch chuyển §ftới chính mình.
Lang_player_not_online: §e【EssentialsTP】 §cNgười chơi không ONLINE.
Lang_sent_request_you: §fGửi cho bạn lời mời dịch chuyển §ftới bạn.
Lang_sent_request_them: §fGửi cho bạn lời mời dịch chuyển §ftới họ.
Lang_accept_request: §e【EssentialsTP】 §fĐể chấp nhận§f lời mời.
Lang_decline_request: §e【EssentialsTP】 §fĐể hủy§f lời mời.
Lang_request_expire_1: §e【EssentialsTP】 §fLời yêu cầu này còn lại§6
Lang_request_expire_2: §fgiây
Lang_request_expire_3: §ftrước khi nó hết hạn.
Lang_type: §e【EssentialsTP】 §fLoại
Lang_no_active_request: §e【EssentialsTP】 §fKhông có lời mời§f nào hoạt động.
Lang_warps: §e【EssentialsTP】 §fCác Khu Dịch Chuyển:§r
Lang_no_warps: §e【EssentialsTP】 §fServer này chưa có§f khu dịch chuyển nào.
Lang_no_warp_listed: §e【EssentialsTP】 §fKhông có warp nào §fmà bạn đã nhập.
Lang_warp_set: §e【EssentialsTP】 §fWarp được đặt là:§6
Lang_warp_to: §e【EssentialsTP】 §fBạn Đã Dịch Chuyển Tới§6
Lang_warp_delete_1: §fTên warp:§6
Lang_warp_delete_2: §fđã bị xoá.
Lang_no_warps_name: §e【EssentialsTP】 §fKhông có khu warp §fnào trùng tên các khu warp§f
  trong server.
Land_chunk_not_loaded: §e【EssentialsTP】 §fKhông thể tải chunk§f, vui lòng báo admin
  để giải quyết.
Lang_action_cooldown: §e【EssentialsTP】 §fHành động này đang trong thời gian hồi§f.
Lang_no_death: §e【EssentialsTP】 §fLàm ơn chết trước khi dùng lệnh này§f.
...
